#!/usr/bin/env tcsh
#===========================================================================
#
# formatAllHC --
# run clang-format on all .H and .C files in the directory
#
# This file is part of the following software:
# 
#    - the low-level C++ template SIMD library
#    - the SIMD implementation of the MinWarping and the 2D-Warping methods 
#      for local visual homing.
# 
# The software is provided based on the accompanying license agreement
# in the file LICENSE or LICENSE.doc. The software is provided "as is"
# without any warranty by the licensor and without any liability of the
# licensor, and the software may not be distributed by the licensee; see
# the license agreement for details.
# 
# (C) Ralf Möller
#     Computer Engineering
#     Faculty of Technology
#     Bielefeld University
#     www.ti.uni-bielefeld.de
#
#===========================================================================

foreach src (`ls -1 *.H *.C`)
        # echo "formatting $src"
        set tmpSrc = tmp_${src}
        clang-format $src > $tmpSrc
        if (`cmp $src $tmpSrc` != "") then
                echo "$src was re-formatted"
        endif
        /bin/cp -f $tmpSrc $src
        /bin/rm -f $tmpSrc
end
