// ===========================================================================
//
// SIMDVecAll.H --
// deprecated common include file for SIMD*.H and Vec*.H
// use tsimd.H instead
//
// This source code file is part of the following software:
//
//    - the low-level C++ template SIMD library
//    - the SIMD implementation of the MinWarping and the 2D-Warping methods
//      for local visual homing.
//
// The software is provided based on the accompanying license agreement
// in the file LICENSE or LICENSE.doc. The software is provided "as is"
// without any warranty by the licensor and without any liability of the
// licensor, and the software may not be distributed by the licensee; see
// the license agreement for details.
//
// (C) Ralf Möller
//     Computer Engineering
//     Faculty of Technology
//     Bielefeld University
//     www.ti.uni-bielefeld.de
//
// ===========================================================================

/**
 * @file SIMDVecAll.H
 * @brief Deprecated main file to include for using the SIMD library. Use
 * tsimd.H instead.
 */

#pragma once
#ifndef SIMD_VEC_ALL_H_
#define SIMD_VEC_ALL_H_

#include "tsimd.H"

#endif
