// ===========================================================================
// 
// SIMDIntrinsNEON.H --
// includes include files for vector intrinsics on ARM CPUs
// 
// This source code file is part of the following software:
// 
//    - the low-level C++ template SIMD library
//    - the SIMD implementation of the MinWarping and the 2D-Warping methods 
//      for local visual homing.
// 
// The software is provided based on the accompanying license agreement
// in the file LICENSE or LICENSE.doc. The software is provided "as is"
// without any warranty by the licensor and without any liability of the
// licensor, and the software may not be distributed by the licensee; see
// the license agreement for details.
// 
// (C) Ralf Möller
//     Computer Engineering
//     Faculty of Technology
//     Bielefeld University
//     www.ti.uni-bielefeld.de
// 
// ===========================================================================

#ifndef _SIMD_INTRINS_NEON_H_
#define _SIMD_INTRINS_NEON_H_

#include "SIMDDefs.H"

#ifdef SIMDVEC_NEON_ENABLE
#include <arm_neon.h>
#endif

#endif // _SIMD_INTRINS_NEON_H_

